import NavBar from "@/components/headers/NavBar";
import Footer from "@/components/footers/footer";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  top,
  second,
  third,
  fourth,
  fifth,
  sixth,
  seventh,
  eight,
}: {
  children: React.ReactNode;
  top: React.ReactNode;
  second: React.ReactNode;
  third: React.ReactNode;
  fourth: React.ReactNode;
  fifth: React.ReactNode;
  sixth: React.ReactNode;
  seventh: React.ReactNode;
  eight: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <NavBar />
          {top}
          {second}
          {third}
          {fourth}
          {fifth}
          {sixth}
          {seventh}
          {eight}
          <Footer />
          {children}
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
